export const FORM_CONFIG = {
  pharmacie: {
    title_fr: 'Pharmacie',
    title_ar: 'صيدلية',
    description_fr: "Demande de licence d'ouverture d'une pharmacie.",
    description_ar: 'طلب رخصة فتح صيدلية.',
    documents: [
      { key: 'cin_proprietaire', label_fr: 'CIN du proprietaire', label_ar: 'بطاقة التعريف الوطنية للمالك', ocr: true,
        ocr_fields: ['nom', 'prenom', 'cin', 'date_naissance', 'adresse', 'commune', 'cercle', 'nom_ar', 'prenom_ar', 'adresse_ar', 'commune_ar', 'cercle_ar'],
        ocr_prompt: "Extrais les données de cette CIN marocaine. La CIN contient des données en français (côté gauche) ET en arabe (côté droit). ⚠ Pour les champs arabes: extrais UNIQUEMENT la valeur sans le label/préfixe. Ex: si tu vois \u0022الدائرة : الخميسات\u0022, retourne \u0022الخميسات\u0022. Extrais: nom (français), prenom (français), commune (français), cercle (français), nom_ar (الاسم العائلي en arabe, valeur uniquement), prenom_ar (الاسم الشخصي en arabe, valeur uniquement), cin, date_naissance (YYYY-MM-DD), adresse (français), adresse_ar (العنوان en arabe, valeur uniquement), commune_ar (الجماعة en arabe, valeur uniquement), cercle_ar (الدائرة en arabe, valeur uniquement). JSON uniquement." },
      { key: 'diplome_pharmacie', label_fr: 'Diplome de pharmacie', label_ar: 'دبلوم الصيدلة', ocr: true,
        ocr_fields: ['nom', 'specialite', 'universite', 'annee', 'nom_ar', 'specialite_ar', 'universite_ar'],
        ocr_prompt: "Extrais les données de ce diplôme. Le document contient du texte en français ET en arabe. ⚠ Pour les champs arabes: extrais UNIQUEMENT la valeur sans le label/préfixe. Extrais: nom (français), nom_ar (arabe, valeur uniquement), specialite (français), specialite_ar (arabe, valeur uniquement), universite (français), universite_ar (arabe, valeur uniquement), annee. JSON uniquement." },
      { key: 'permis_exercice', label_fr: "Permis d'exercice", label_ar: 'رخصة المزاولة', ocr: true,
        ocr_fields: ['numero_permis', 'date_permis'],
        ocr_prompt: 'Extrais numero_permis, date_permis (YYYY-MM-DD). JSON uniquement.' },
      { key: 'certificat_distance', label_fr: 'Certificat de distance', label_ar: 'شهادة المسافة', ocr: false },
      { key: 'pv_commission', label_fr: 'PV de la commission', label_ar: 'محضر اللجنة', ocr: false },
    ],
    sections: [
      {
        title_fr: 'Informations personnelles',
        title_ar: 'المعلومات الشخصية',
        fields: [
          { name: 'nom_complet', label_fr: 'Nom complet', label_ar: 'الاسم الكامل', type: 'text', required: true, arabic: true },
          { name: 'cin', label_fr: 'CIN', label_ar: 'رقم بطاقة التعريف', type: 'text', required: true, transform: 'uppercase' },
          { name: 'date_naissance', label_fr: 'Date de naissance', label_ar: 'تاريخ الازدياد', type: 'date' },
          { name: 'universite', label_fr: 'Universite', label_ar: 'الجامعة', type: 'text', arabic: true },
          { name: 'diplome', label_fr: 'Diplome', label_ar: 'الشهادة', type: 'text', arabic: true },
        ],
      },
      {
        title_fr: 'Details de la demande',
        title_ar: 'تفاصيل الطلب',
        fields: [
          { name: 'adresse_complete', label_fr: 'Adresse de la pharmacie', label_ar: 'عنوان الصيدلية', type: 'textarea', required: true, arabic: true },
          { name: 'commune', label_fr: 'Commune', label_ar: 'الجماعة', type: 'text', required: true, arabic: true },
          { name: 'cercle', label_fr: 'Cercle', label_ar: 'الدائرة', type: 'text', required: true, arabic: true },
          { name: 'numero_izin', label_fr: "Numero de permis", label_ar: 'رقم الرخصة', type: 'text' },
          { name: 'date_izin', label_fr: 'Date de permis', label_ar: 'تاريخ الرخصة', type: 'date' },
          { name: 'nom_massah', label_fr: 'Geometre', label_ar: 'المسّاح', type: 'text', arabic: true },
          { name: 'date_massah', label_fr: 'Date certificat', label_ar: 'تاريخ الشهادة', type: 'date' },
          { name: 'date_lajna', label_fr: 'Date commission', label_ar: 'تاريخ اللجنة', type: 'date' },
        ],
      },
    ],
  },

  cafe_restaurant: {
    title_fr: 'Cafe / Restaurant',
    title_ar: 'مقهى / مطعم',
    description_fr: "Demande de licence d'exploitation d'un cafe ou restaurant.",
    description_ar: 'طلب رخصة استغلال مقهى أو مطعم.',
    documents: [
      { key: 'cin_proprietaire', label_fr: 'CIN du proprietaire', label_ar: 'بطاقة التعريف الوطنية للمالك', ocr: true,
        ocr_fields: ['nom', 'prenom', 'cin', 'date_naissance', 'adresse', 'commune', 'cercle', 'nom_ar', 'prenom_ar', 'adresse_ar', 'commune_ar', 'cercle_ar'],
        ocr_prompt: "Extrais les données de cette CIN marocaine. La CIN contient des données en français (côté gauche) ET en arabe (côté droit). ⚠ Pour les champs arabes: extrais UNIQUEMENT la valeur sans le label/préfixe. Ex: si tu vois \u0022الدائرة : الخميسات\u0022, retourne \u0022الخميسات\u0022. Extrais: nom (français), prenom (français), commune (français), cercle (français), nom_ar (الاسم العائلي en arabe, valeur uniquement), prenom_ar (الاسم الشخصي en arabe, valeur uniquement), cin, date_naissance (YYYY-MM-DD), adresse (français), adresse_ar (العنوان en arabe, valeur uniquement), commune_ar (الجماعة en arabe, valeur uniquement), cercle_ar (الدائرة en arabe, valeur uniquement). JSON uniquement." },
      { key: 'bail_propriete', label_fr: 'Bail ou titre de propriete', label_ar: 'عقد الكراء أو سند الملكية', ocr: true,
        ocr_fields: ['adresse_local', 'superficie', 'nom_proprietaire', 'adresse_local_ar', 'nom_proprietaire_ar'],
        ocr_prompt: "Extrais les données de ce bail ou titre de propriété. ⚠ Pour les champs arabes: extrais UNIQUEMENT la valeur sans le label/préfixe. Extrais: adresse_local (français), adresse_local_ar (arabe, valeur uniquement), superficie (nombre m2), nom_proprietaire (français), nom_proprietaire_ar (arabe, valeur uniquement). JSON uniquement." },
      { key: 'certificat_conformite', label_fr: 'Certificat de conformite', label_ar: 'شهادة المطابقة', ocr: false },
      { key: 'autorisation_exploitation', label_fr: "Autorisation d'exploitation", label_ar: 'رخصة الاستغلال', ocr: false },
      { key: 'plan_local', label_fr: 'Plan du local', label_ar: 'مخطط المحل', ocr: false },
      { key: 'attestation_sanitize', label_fr: 'Attestation sanitaire', label_ar: 'شهادة صحية', ocr: false },
    ],
    sections: [
      {
        title_fr: 'Informations personnelles',
        title_ar: 'المعلومات الشخصية',
        fields: [
          { name: 'nom', label_fr: 'Nom', label_ar: 'الاسم العائلي', type: 'text', required: true, arabic: true },
          { name: 'prenom', label_fr: 'Prenom', label_ar: 'الاسم الشخصي', type: 'text', required: true, arabic: true },
          { name: 'cin', label_fr: 'CIN', label_ar: 'رقم بطاقة التعريف', type: 'text', required: true, transform: 'uppercase' },
          { name: 'date_naissance', label_fr: 'Date de naissance', label_ar: 'تاريخ الازدياد', type: 'date', required: true },
          { name: 'adresse_proprietaire', label_fr: 'Adresse du proprietaire', label_ar: 'عنوان المالك', type: 'textarea', required: true, arabic: true },
        ],
      },
      {
        title_fr: 'Details de la demande',
        title_ar: 'تفاصيل الطلب',
        fields: [
          { name: 'adresse_local', label_fr: 'Adresse du local', label_ar: 'عنوان المحل', type: 'textarea', required: true, arabic: true },
          { name: 'commune', label_fr: 'Commune', label_ar: 'الجماعة', type: 'text', required: true, arabic: true },
          { name: 'cercle', label_fr: 'Cercle', label_ar: 'الدائرة', type: 'text', required: true, arabic: true },
          { name: 'superficie', label_fr: 'Superficie (m2)', label_ar: 'المساحة (م2)', type: 'number', required: true },
          { name: 'capacite_places', label_fr: 'Capacite (nombre de places)', label_ar: 'الطاقة الاستيعابية', type: 'number', required: true },
          {
            name: 'type_etablissement',
            label_fr: "Type d'etablissement",
            label_ar: 'نوع المؤسسة',
            type: 'select',
            required: true,
            options: ['Cafe', 'Restaurant', 'Cafe-Restaurant', 'Fast-food', 'Snack'],
          },
        ],
      },
      {
        title_fr: 'Coordonnees',
        title_ar: 'معلومات الاتصال',
        fields: [
          { name: 'telephone', label_fr: 'Telephone', label_ar: 'الهاتف', type: 'tel' },
          { name: 'email', label_fr: 'Email', label_ar: 'البريد الإلكتروني', type: 'email' },
        ],
      },
    ],
  },

  hopital_clinique: {
    title_fr: 'Hopital / Clinique',
    title_ar: 'مستشفى / عيادة',
    description_fr: "Demande de licence d'ouverture d'un etablissement de soins.",
    description_ar: 'طلب رخصة فتح مؤسسة صحية.',
    documents: [
      { key: 'cin_directeur', label_fr: 'CIN du directeur medical', label_ar: 'بطاقة التعريف الوطنية للمدير الطبي', ocr: true,
        ocr_fields: ['nom', 'prenom', 'cin', 'date_naissance', 'adresse', 'commune', 'cercle', 'nom_ar', 'prenom_ar', 'adresse_ar', 'commune_ar', 'cercle_ar'],
        ocr_prompt: "Extrais les données de cette CIN marocaine. La CIN contient des données en français (côté gauche) ET en arabe (côté droit). ⚠ Pour les champs arabes: extrais UNIQUEMENT la valeur sans le label/préfixe. Ex: si tu vois \u0022الدائرة : الخميسات\u0022, retourne \u0022الخميسات\u0022. Extrais: nom (français), prenom (français), commune (français), cercle (français), nom_ar (الاسم العائلي en arabe, valeur uniquement), prenom_ar (الاسم الشخصي en arabe, valeur uniquement), cin, date_naissance (YYYY-MM-DD), adresse (français), adresse_ar (العنوان en arabe, valeur uniquement), commune_ar (الجماعة en arabe, valeur uniquement), cercle_ar (الدائرة en arabe, valeur uniquement). JSON uniquement." },
      { key: 'diplome_medecin', label_fr: 'Diplome de medecine / specialite', label_ar: 'دبلوم الطب / التخصص', ocr: true,
        ocr_fields: ['nom', 'specialite', 'universite', 'annee', 'nom_ar', 'specialite_ar', 'universite_ar'],
        ocr_prompt: "Extrais les données de ce diplôme médical. Le document contient du texte en français ET en arabe. ⚠ Pour les champs arabes: extrais UNIQUEMENT la valeur sans le label/préfixe. Extrais: nom (français), nom_ar (arabe, valeur uniquement), specialite (français), specialite_ar (arabe, valeur uniquement), universite (français), universite_ar (arabe, valeur uniquement), annee. JSON uniquement." },
      { key: 'autorisation_exploitation', label_fr: "Autorisation d'exploitation", label_ar: 'رخصة الاستغلال', ocr: true,
        ocr_fields: ['numero_autorisation', 'date_autorisation'],
        ocr_prompt: 'Extrais numero_autorisation, date_autorisation (YYYY-MM-DD). JSON uniquement.' },
      { key: 'plan_architectural', label_fr: 'Plan architectural', label_ar: 'المخطط المعماري', ocr: false },
      { key: 'certificat_conformite_incendie', label_fr: 'Certificat de conformite incendie', label_ar: 'شهادة مطابقة الوقاية من الحريق', ocr: false },
      { key: 'liste_equipements_medicaux', label_fr: 'Liste des equipements medicaux', label_ar: 'قائمة التجهيزات الطبية', ocr: false },
    ],
    sections: [
      {
        title_fr: 'Directeur medical',
        title_ar: 'المدير الطبي',
        fields: [
          { name: 'nom_directeur', label_fr: 'Nom du directeur medical', label_ar: 'اسم المدير الطبي', type: 'text', required: true, arabic: true },
          { name: 'prenom_directeur', label_fr: 'Prenom du directeur medical', label_ar: 'الاسم الشخصي للمدير الطبي', type: 'text', required: true, arabic: true },
          { name: 'cin_directeur', label_fr: 'CIN du directeur', label_ar: 'بطاقة التعريف للمدير', type: 'text', required: true, transform: 'uppercase' },
          { name: 'specialite', label_fr: 'Specialite', label_ar: 'التخصص', type: 'text', required: true, arabic: true },
          { name: 'numero_autorisation', label_fr: "Numero d'autorisation", label_ar: 'رقم الترخيص', type: 'text' },
        ],
      },
      {
        title_fr: 'Details de la demande',
        title_ar: 'تفاصيل الطلب',
        fields: [
          { name: 'nom_clinique', label_fr: "Nom de l'hopital / clinique", label_ar: 'اسم المستشفى / العيادة', type: 'text', required: true, arabic: true },
          { name: 'adresse', label_fr: 'Adresse', label_ar: 'العنوان', type: 'textarea', required: true, arabic: true },
          { name: 'commune', label_fr: 'Commune', label_ar: 'الجماعة', type: 'text', required: true, arabic: true },
          { name: 'cercle', label_fr: 'Cercle', label_ar: 'الدائرة', type: 'text', required: true, arabic: true },
          { name: 'superficie', label_fr: 'Superficie (m2)', label_ar: 'المساحة (م2)', type: 'number', required: true },
          { name: 'nombre_lits', label_fr: 'Nombre de lits', label_ar: 'عدد الأسرة', type: 'number', required: true },
          {
            name: 'type_clinique',
            label_fr: 'Type de clinique',
            label_ar: 'نوع العيادة',
            type: 'select',
            required: true,
            options: ['Clinique generale', 'Clinique specialisee', 'Hopital prive', 'Centre de soins', 'Polyclinique'],
          },
          { name: 'specialites_proposees', label_fr: 'Specialites proposees', label_ar: 'التخصصات المقدمة', type: 'textarea', arabic: true },
        ],
      },
      {
        title_fr: 'Coordonnees',
        title_ar: 'معلومات الاتصال',
        fields: [
          { name: 'telephone', label_fr: 'Telephone', label_ar: 'الهاتف', type: 'tel' },
          { name: 'email', label_fr: 'Email', label_ar: 'البريد الإلكتروني', type: 'email' },
        ],
      },
    ],
  },

  ecole_privee: {
    title_fr: 'Ecole privee',
    title_ar: 'مدرسة خاصة',
    description_fr: "Demande de licence d'ouverture d'un etablissement scolaire prive.",
    description_ar: 'طلب رخصة فتح مؤسسة تعليمية خاصة.',
    documents: [
      { key: 'cin_directeur', label_fr: 'CIN du directeur', label_ar: 'بطاقة التعريف الوطنية للمدير', ocr: true,
        ocr_fields: ['nom', 'prenom', 'cin', 'date_naissance', 'adresse', 'commune', 'cercle', 'nom_ar', 'prenom_ar', 'adresse_ar', 'commune_ar', 'cercle_ar'],
        ocr_prompt: "Extrais les données de cette CIN marocaine. La CIN contient des données en français (côté gauche) ET en arabe (côté droit). ⚠ Pour les champs arabes: extrais UNIQUEMENT la valeur sans le label/préfixe. Ex: si tu vois \u0022الدائرة : الخميسات\u0022, retourne \u0022الخميسات\u0022. Extrais: nom (français), prenom (français), commune (français), cercle (français), nom_ar (الاسم العائلي en arabe, valeur uniquement), prenom_ar (الاسم الشخصي en arabe, valeur uniquement), cin, date_naissance (YYYY-MM-DD), adresse (français), adresse_ar (العنوان en arabe, valeur uniquement), commune_ar (الجماعة en arabe, valeur uniquement), cercle_ar (الدائرة en arabe, valeur uniquement). JSON uniquement." },
      { key: 'diplome_directeur', label_fr: 'Diplome du directeur', label_ar: 'دبلوم المدير', ocr: true,
        ocr_fields: ['nom', 'specialite', 'universite', 'annee', 'nom_ar', 'specialite_ar', 'universite_ar'],
        ocr_prompt: "Extrais les données de ce diplôme. Le document contient du texte en français ET en arabe. ⚠ Pour les champs arabes: extrais UNIQUEMENT la valeur sans le label/préfixe. Extrais: nom (français), nom_ar (arabe, valeur uniquement), specialite (français), specialite_ar (arabe, valeur uniquement), universite (français), universite_ar (arabe, valeur uniquement), annee. JSON uniquement." },
      { key: 'bail_propriete', label_fr: 'Bail ou titre de propriete', label_ar: 'عقد الكراء أو سند الملكية', ocr: false },
      { key: 'plans_locaux', label_fr: 'Plans des locaux', label_ar: 'مخططات المحلات', ocr: false },
      { key: 'liste_enseignants', label_fr: 'Liste des enseignants', label_ar: 'قائمة الأساتذة', ocr: false },
      { key: 'attestation_conformite_salles', label_fr: 'Attestation de conformite des salles', label_ar: 'شهادة مطابقة القاعات', ocr: false },
    ],
    sections: [
      {
        title_fr: "Directeur de l'ecole",
        title_ar: 'مدير المدرسة',
        fields: [
          { name: 'nom_directeur', label_fr: 'Nom du directeur', label_ar: 'اسم المدير', type: 'text', required: true, arabic: true },
          { name: 'prenom_directeur', label_fr: 'Prenom du directeur', label_ar: 'الاسم الشخصي للمدير', type: 'text', required: true, arabic: true },
          { name: 'cin_directeur', label_fr: 'CIN du directeur', label_ar: 'بطاقة التعريف للمدير', type: 'text', required: true, transform: 'uppercase' },
          { name: 'diplome_directeur', label_fr: 'Diplome du directeur', label_ar: 'دبلوم المدير', type: 'text', required: true, arabic: true },
          { name: 'experience_annees', label_fr: 'Experience (annees)', label_ar: 'الخبرة (سنوات)', type: 'number' },
        ],
      },
      {
        title_fr: 'Details de la demande',
        title_ar: 'تفاصيل الطلب',
        fields: [
          { name: 'nom_ecole', label_fr: "Nom de l'ecole", label_ar: 'اسم المدرسة', type: 'text', required: true, arabic: true },
          { name: 'adresse', label_fr: 'Adresse', label_ar: 'العنوان', type: 'textarea', required: true, arabic: true },
          { name: 'commune', label_fr: 'Commune', label_ar: 'الجماعة', type: 'text', required: true, arabic: true },
          { name: 'cercle', label_fr: 'Cercle', label_ar: 'الدائرة', type: 'text', required: true, arabic: true },
          { name: 'superficie_totale', label_fr: 'Superficie totale (m2)', label_ar: 'المساحة الإجمالية (م2)', type: 'number', required: true },
          {
            name: 'cycle',
            label_fr: "Cycle d'enseignement",
            label_ar: 'مستوى التعليم',
            type: 'select',
            required: true,
            options: ['Prescolaire', 'Primaire', 'College', 'Lycee', 'Prescolaire + Primaire', 'Tous cycles'],
          },
          { name: 'nombre_classes', label_fr: 'Nombre de classes', label_ar: 'عدد الأقسام', type: 'number', required: true },
          { name: 'capacite_eleves', label_fr: 'Capacite eleves', label_ar: 'الطاقة الاستيعابية للتلاميذ', type: 'number', required: true },
        ],
      },
      {
        title_fr: 'Coordonnees',
        title_ar: 'معلومات الاتصال',
        fields: [
          { name: 'telephone', label_fr: 'Telephone', label_ar: 'الهاتف', type: 'tel' },
          { name: 'email', label_fr: 'Email', label_ar: 'البريد الإلكتروني', type: 'email' },
        ],
      },
    ],
  },

  salle_sport: {
    title_fr: 'Salle de sport',
    title_ar: 'قاعة رياضية',
    description_fr: "Demande de licence d'ouverture d'une salle de sport.",
    description_ar: 'طلب رخصة فتح قاعة رياضية.',
    documents: [
      { key: 'cin_proprietaire', label_fr: 'CIN du proprietaire', label_ar: 'بطاقة التعريف الوطنية للمالك', ocr: true,
        ocr_fields: ['nom', 'prenom', 'cin', 'date_naissance', 'adresse', 'commune', 'cercle', 'nom_ar', 'prenom_ar', 'adresse_ar', 'commune_ar', 'cercle_ar'],
        ocr_prompt: "Extrais les données de cette CIN marocaine. La CIN contient des données en français (côté gauche) ET en arabe (côté droit). ⚠ Pour les champs arabes: extrais UNIQUEMENT la valeur sans le label/préfixe. Ex: si tu vois \u0022الدائرة : الخميسات\u0022, retourne \u0022الخميسات\u0022. Extrais: nom (français), prenom (français), commune (français), cercle (français), nom_ar (الاسم العائلي en arabe, valeur uniquement), prenom_ar (الاسم الشخصي en arabe, valeur uniquement), cin, date_naissance (YYYY-MM-DD), adresse (français), adresse_ar (العنوان en arabe, valeur uniquement), commune_ar (الجماعة en arabe, valeur uniquement), cercle_ar (الدائرة en arabe, valeur uniquement). JSON uniquement." },
      { key: 'bail_propriete', label_fr: 'Bail ou titre de propriete', label_ar: 'عقد الكراء أو سند الملكية', ocr: false },
      { key: 'diplome_education_physique', label_fr: "Diplome d'education physique", label_ar: 'دبلوم التربية البدنية', ocr: true,
        ocr_fields: ['nom', 'specialite', 'universite', 'annee', 'nom_ar', 'specialite_ar', 'universite_ar'],
        ocr_prompt: "Extrais les données de ce diplôme sportif. Le document contient du texte en français ET en arabe. ⚠ Pour les champs arabes: extrais UNIQUEMENT la valeur sans le label/préfixe. Extrais: nom (français), nom_ar (arabe, valeur uniquement), specialite (français), specialite_ar (arabe, valeur uniquement), universite (français), universite_ar (arabe, valeur uniquement), annee. JSON uniquement." },
      { key: 'attestation_conformite_equipements', label_fr: 'Attestation de conformite des equipements', label_ar: 'شهادة مطابقة التجهيزات', ocr: false },
      { key: 'plan_local', label_fr: 'Plan des locaux', label_ar: 'مخطط المحل', ocr: false },
      { key: 'certificat_medical', label_fr: 'Certificat medical du responsable', label_ar: 'الشهادة الطبية للمسؤول', ocr: false },
    ],
    sections: [
      {
        title_fr: 'Informations personnelles',
        title_ar: 'المعلومات الشخصية',
        fields: [
          { name: 'nom', label_fr: 'Nom', label_ar: 'الاسم العائلي', type: 'text', required: true, arabic: true },
          { name: 'prenom', label_fr: 'Prenom', label_ar: 'الاسم الشخصي', type: 'text', required: true, arabic: true },
          { name: 'cin', label_fr: 'CIN', label_ar: 'رقم بطاقة التعريف', type: 'text', required: true, transform: 'uppercase' },
          { name: 'qualification_sportive', label_fr: 'Qualification sportive', label_ar: 'المؤهل الرياضي', type: 'text', required: true, arabic: true },
        ],
      },
      {
        title_fr: 'Details de la demande',
        title_ar: 'تفاصيل الطلب',
        fields: [
          { name: 'nom_salle', label_fr: 'Nom de la salle', label_ar: 'اسم القاعة', type: 'text', required: true, arabic: true },
          { name: 'adresse', label_fr: 'Adresse', label_ar: 'العنوان', type: 'textarea', required: true, arabic: true },
          { name: 'commune', label_fr: 'Commune', label_ar: 'الجماعة', type: 'text', required: true, arabic: true },
          { name: 'cercle', label_fr: 'Cercle', label_ar: 'الدائرة', type: 'text', required: true, arabic: true },
          { name: 'superficie', label_fr: 'Superficie (m2)', label_ar: 'المساحة (م2)', type: 'number', required: true },
          {
            name: 'type_activites',
            label_fr: "Type d'activites",
            label_ar: 'نوع الأنشطة',
            type: 'select',
            required: true,
            options: ['Musculation', 'Arts martiaux', 'Fitness / Cardio', 'Natation', 'Sports collectifs', 'Multi-activites'],
          },
          { name: 'capacite_membres', label_fr: 'Capacite membres', label_ar: 'الطاقة الاستيعابية للأعضاء', type: 'number', required: true },
          { name: 'equipements_disponibles', label_fr: 'Equipements disponibles', label_ar: 'التجهيزات المتوفرة', type: 'textarea', arabic: true },
        ],
      },
      {
        title_fr: 'Coordonnees',
        title_ar: 'معلومات الاتصال',
        fields: [
          { name: 'telephone', label_fr: 'Telephone', label_ar: 'الهاتف', type: 'tel' },
          { name: 'email', label_fr: 'Email', label_ar: 'البريد الإلكتروني', type: 'email' },
        ],
      },
    ],
  },
};
